name: Release

on:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24'
          cache: pnpm
          scope: '@morev'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Linting
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Testing
        run: pnpm test

      - name: Build the module
        run: pnpm build

      - name: Getting latest changelog entry
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        id: latest-changelog-entry
        with:
          result-encoding: string
          script: |
            const extractLatestChangelogEntry = require('./.github/extract-latest-changelog-entry.cjs');
            return extractLatestChangelogEntry();

      - name: Create release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: ${{steps.latest-changelog-entry.outputs.result}}

      - name: Publish package
        run: pnpm publish --provenance --access public --no-git-checks
